=head1 NAME 

Manual

=head1 SYNOPSIS


#!/usr/bin/perl 

use strict;
use warnings;

sub post_to_accounts (Account $account1, Account $account2) {
	scream("Debits and Credits dont equal!!!!") unless (sum(@debits) == sum(@credits));
	
	txn_do {
		$account1->post;
		$account2->post;
	}
	
}


my $account1 = F::A::Account->new(101);
my $account2 = F::A::Account->new(201);

$account1->debit($amount) and push @debits, $amount;
$account2->credit($amount) and push @credit, $amount;


=head1 CONCEPTS

=over 4

=item

Accounts need only have one property; balance.

=item

Accounts need to be of type debit or credit to know how whether $acct->debit or $acct->credit is an addition or subtraction to the current balance of that account.

=back

=head2 Structure

=over 2

=item

A Ledger contains Entries. Entries contain AT LEAST one account to debit and one account to credit where the total of debits equals the total of credits; such that DEBITS - CREDITS = 0

=back

=cut
